"use strict";
var _a, _b, _c, _d, _e, _f, _g, _h;
Object.defineProperty(exports, "__esModule", { value: true });
exports.supabase = void 0;
require("react-native-url-polyfill/auto");
var supabase_js_1 = require("@supabase/supabase-js");
var expo_constants_1 = require("expo-constants");
var supabaseUrl = (_d = (_c = (_b = (_a = expo_constants_1.default.expoConfig) === null || _a === void 0 ? void 0 : _a.extra) === null || _b === void 0 ? void 0 : _b.EXPO_PUBLIC_SUPABASE_URL) !== null && _c !== void 0 ? _c : process.env.EXPO_PUBLIC_SUPABASE_URL) !== null && _d !== void 0 ? _d : '';
var supabaseAnonKey = (_h = (_g = (_f = (_e = expo_constants_1.default.expoConfig) === null || _e === void 0 ? void 0 : _e.extra) === null || _f === void 0 ? void 0 : _f.EXPO_PUBLIC_SUPABASE_ANON_KEY) !== null && _g !== void 0 ? _g : process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY) !== null && _h !== void 0 ? _h : '';
exports.supabase = (0, supabase_js_1.createClient)(supabaseUrl, supabaseAnonKey);
